version: 2
executorType: docker
jobs:
  build:
    docker:
      - image: python:3.7.4-stretch
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install Test Dependencies
          command: pip install pytest pytest-cov
      - run:
          name: Test
          command: |
            PYTHONPATH=. pytest --cov=./
            codecov
